name: wechat
description: Flutter即时通讯APP界面实现

dependencies:
  flutter:
    sdk: flutter

  flutter_webview_plugin: "^0.3.0+2"
  date_format: "^1.0.4"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:

  #加载页面图片资源
  - images/loading.jpeg

  #底部tab切换图片资源
  - images/contact_list_normal.png
  - images/contact_list_pressed.png
  - images/profile_normal.png
  - images/profile_pressed.png
  - images/message_normal.png
  - images/message_pressed.png

  #菜单按钮
  - images/icon_menu_addfriend.png
  - images/icon_menu_group.png

  #好友模块图标
  - images/icon_addfriend.png
  - images/icon_groupchat.png
  - images/icon_public.png

  #我的模块图标
  - images/icon_me_friends.png
  - images/icon_me_photo.png
  - images/icon_me_file.png
  - images/icon_me_service.png
  - images/icon_me_message.png
  - images/icon_me_clear.png
  - images/code.png
  - images/yixiu.jpeg



