export 'package:app/pages/customer_service/customer_service_page.dart';
export 'package:app/pages/home/home_page.dart';
export 'package:app/pages/login/login_page.dart';
export 'package:app/pages/login/bind_page.dart';
export 'package:app/pages/login/register_page.dart';
export 'package:app/pages/manager/manager.dart';
export 'package:app/pages/me/my_page.dart';
export 'package:app/pages/splash/splash.dart';
export 'package:app/navigator/tab_navigator.dart';
