name: app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.4
  dio: ^2.1.0 #网络库
  crypto: ^2.0.6  #md5加密
  url_launcher: ^3.0.3  #拨打电话
  package_info: ^0.4.0+4  #设备信息
  uuid: 2.0.1 #uuid
  shared_preferences: ^0.4.3  # 本地存储、收藏功能
  fluwx: ^0.6.3 #微信
  image_gallery_saver: ^1.1.0
  permission_handler: ^3.0.1
  image_saver: ^1.0.0
  http: ^0.12.0+2
  event_bus: ^1.1.0
  common_utils: '>=1.1.0 <3.0.0' # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  json2entity: ^1.0.6
  flutter_spinkit: ^3.1.0 #loading
  flutter_html: ^0.10.4 #富文本内容显示
  tobias: ^1.0.0+1 #支付宝支付
  extended_image: ^0.5.1 # 图片预览，缩放
  flutter_lifecycle_state: ^1.0.0  #  仿Android生命周期
  pull_to_refresh: ^1.4.8  # 下拉刷新和上拉加载
  amap_base: ^0.3.5  # 高德地图

  cached_network_image:
    git: https://github.com/openjmu/flutter_cached_network_image.git  # 0.8.0

  flutter_cache_manager:
    git: https://github.com/openjmu/flutter_cache_manager.git  # 0.3.2

  gzx_dropdown_menu:
      git:
        url: https://github.com/GanZhiXiong/gzx_dropdown_menu.git

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
